version: 1
disable_existing_loggers: False

formatters:
    default:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: default
        stream: ext://sys.stdout

loggers:
    development:
        level: DEBUG
        handlers: [console]
        propagate: no

    staging:
        level: INFO
        handlers: [console]
        propagate: no

    production:
        level: WARNING
        handlers: [console]
        propagate: no

root:
    level: DEBUG
    handlers: [console]