name: CI

on:
  push:
    branches: [ "feature/CI-pipeline" ]

jobs:
  run-unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.8"
          # - "3.9"
    
    name: Test
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r joke-service/requirements.txt

    - name: Run unit tests for the Joke Service
      run: pytest